# Generated by Django 5.2.16 on 2026-07-16 06:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_example_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('layer_type', models.CharField(choices=[('vector', 'Vecteur'), ('raster', 'Raster')], default='vector', max_length=10)),
                ('origin', models.CharField(choices=[('upload', 'Import'), ('meteofrance', 'Météo-France'), ('calcul', 'Calcul')], default='upload', max_length=20)),
                ('srid_source', models.IntegerField(blank=True, null=True)),
                ('geom_type', models.CharField(blank=True, max_length=32)),
                ('feature_count', models.IntegerField(default=0)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('raster_file', models.FileField(blank=True, null=True, upload_to='rasters/')),
                ('published_qgis', models.BooleanField(default=False)),
                ('owner_email', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'layers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userrecord',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.layer')),
            ],
            options={
                'db_table': 'features',
            },
        ),
    ]
